### PR TITLE
support psycopg 2.8 and sqlalchemy 1.3

### PR DESCRIPTION
**Pull request by mozartilize**
* psycopg 2.8 adds connection info so sqlalchemy connection fairy info
    will be assigned to it
* sqlalchemy 1.3 deprecated pool.manage so we move the pool
    to databasewrapper object
        + add option `DATABASE_POOL_CLASS` to choose which pool class
        will be constructed

### CODE REVIEW

**Comment by lcd1232** [comment]
Thanks for your PR

**Comment by smagafurov** [comment]
@lcd1232 Hi!
Can you release this?
On pypi "Last released: Feb 13, 2018"

**Comment by mozartilize** [comment]
@smagafurov hi, currently master is not stable because it creates new pool on every thread, i have new patch that not being review, you might take a look over it if interested

**Comment by smagafurov** [comment]
Ok

**Pull request merged**
