### PR TITLE
Disable psycopg2 parsing JSONField value on Django 3.1+

### LINKED ISSUE #25: JSONField error in model
I have a model which uses json field like this:
```
...
score = models.JSONField(null=True, blank=True, default={})
...
```
Which works correctly when using `django.db.backends.postgresql` as DB_ENGINE, but when change it to `django_postgrespool2`, I got following error:
```
Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
response = get_response(request)
File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/usr/local/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
return view_func(*args, **kwargs)
File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
return self.dispatch(request, *args, **kwargs)
File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
response = self.handle_exception(exc)
File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
self.raise_uncaught_exception(exc)
File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
raise exc
File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
response = handler(request, *args, **kwargs)
File "/app/src/account/api/v1/views/profile.py", line 39, in post
page = self.paginate_queryset(queryset)
File "/usr/local/lib/python3.8/site-packages/rest_framework/generics.py", line 171, in paginate_queryset
return self.paginator.paginate_queryset(queryset, self.request, view=self)
File "/usr/local/lib/python3.8/site-packages/rest_framework/pagination.py", line 216, in paginate_queryset
return list(self.page)
File "/usr/local/lib/python3.8/_collections_abc.py", line 874, in __iter__
v = self[i]
File "/usr/local/lib/python3.8/site-packages/django/core/paginator.py", line 188, in __getitem__
self.object_list = list(self.object_list)
File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 280, in __iter__
self._fetch_all()
File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 1324, in _fetch_all
self._result_cache = list(self._iterable_class(self))
File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 68, in __iter__
for row in compiler.results_iter(results):
File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1122, in apply_converters
value = converter(value, expression, connection)
File "/usr/local/lib/python3.8/site-packages/django/db/models/fields/json.py", line 83, in from_db_value
return json.loads(value, cls=self.decoder)
File "/usr/local/lib/python3.8/json/__init__.py", line 341, in loads
raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not dict
```

P.S. In one of my old projects, I was using  `django_postgrespool` (the deprecated package) and it had no issues with JSONField as well.

### PR DESCRIPTION
**Pull request by rvause**
Fixes #25; related change in Django project https://github.com/django/django/pull/13358

### CODE REVIEW

**Comment by lcd1232-epam** [comment]
@rvause thank you for your PR. Give me some time to review it

**Comment by lcd1232** [comment]
@rvause thank you for your PR. Give me some time to review it

**Comment by aa403** [comment]
I also hit this issue, and then found this -- it looks sensible to me - any view on when we can have a release?

**Comment by samul-1** [comment]
Bump; pr looks okay, any info on when this'll be released?

**Pull request merged**
